export const PERMISSIONS = {
  CREATE_RECORD: "create_record",
  VIEW_RECORD: "view_record",
  UPDATE_RECORD: "update_record",
  DELETE_RECORD: "delete_record",
  VIEW_SUMMARY: "view_summary",
  MANAGE_USERS: "manage_users"
};

export const ROLE_PERMISSIONS = {
  VIEWER: [
    PERMISSIONS.VIEW_SUMMARY
  ],

  ANALYST: [
    PERMISSIONS.VIEW_RECORD,
    PERMISSIONS.VIEW_SUMMARY
  ],

  ADMIN: [
    PERMISSIONS.CREATE_RECORD,
    PERMISSIONS.VIEW_RECORD,
    PERMISSIONS.UPDATE_RECORD,
    PERMISSIONS.DELETE_RECORD,
    PERMISSIONS.VIEW_SUMMARY,
    PERMISSIONS.MANAGE_USERS
  ]
};